### ISSUE TITLE
Problem with menu location

### ISSUE THREAD

**Issue by Georgopoulos** [webmandesign/classic-menu-in-navigation-block#1]
Hey there!

First of all, congratulations for this plugin! It has been the ONLY solution I've found so far to support multilingual menus in the new Wordpress block editor. 🙏 

I am facing the following issue though and I am not sure if this is a problem of this plugin or my theme's...

I am using Polylang and I have 2 languages set up, English and Greek. My theme originally has 3 menu locations which are duplicated since I have 2 languages, so 6 in total. 

For the default language (Greek) my classic menu appears perfectly:

<img width="500" alt="image" src="https://github.com/webmandesign/classic-menu-in-navigation-block/assets/6174137/52995298-94aa-4e78-b969-2b909a2ba325">

For the second language though (English) this happens:

<img width="436" alt="image" src="https://github.com/webmandesign/classic-menu-in-navigation-block/assets/6174137/3122d55b-b8c8-4dd4-8315-3d0074716e66">

Could this be an issue with this plugin..?

Thanks in advance!

**Comment by webmandesign** [comment]
Hi @Georgopoulos,

Thank you, I'm glad you like the plugin and consider it helpful. 

Please allow me to test and investigate and I will get back to you soon.
From the top of my head there may be some setup issue here as I've tested the plugin with Polylang and it was working perfectly fine.

**Comment by webmandesign** [comment]
One additional question. You mention:
> My theme originally has 3 menu locations

Can you let me know which theme you are using?

The plugin was built for block themes (full site editing themes) and they don't actually have any classic menu locations registered.
However, the plugin does register 3 menu locations: Primary, Secondary and Tertiary by default.

Can you provide screenshot of your **Appearance → Menus → Manage Locations** screen?

**Comment by Georgopoulos** [comment]
Here is a screenshot of the menu locations:
![image](https://github.com/webmandesign/classic-menu-in-navigation-block/assets/6174137/c98d691b-59d7-4e11-bdf9-5aa2cc7a2a25)

I am using the [Inspiro Block](https://www.wpzoom.com/themes/inspiro-blocks/) theme

**Comment by webmandesign** [comment]
Thank you for the screenshot. It looks perfectly fine.

I've tested the plugin with Twenty Twenty-Four and Inspiro Blocks theme and it works perfectly fine for me.

Here are some tips you can try:

1. Make sure the "Main menu EN" contains some menu items.
2. Try to save some classic menu again to refresh the cache.
3. There is an issue regarding the Inspiro Blocks theme as by default it displays pages list in navigation and you need to set some custom menu for it first (see the GIF below), otherwise the plugin won't work for the theme. But from your screenshot I'd say this is not the issue on your website probably.

![inspiro-block-theme-navigation](https://github.com/webmandesign/classic-menu-in-navigation-block/assets/2456735/60da72b9-043e-4746-aa05-33e8fa3089cc)


If none of the above works, please provide an access to your website so I can check personally - use [a contact form at my website](https://www.webmandesign.eu/contact/) to provide access details.

**Comment by Georgopoulos** [comment]
Hey @webmandesign ! Thanks so much for your time and the effort you put on my problem.
Both menus contain menu items in my case. Primary English works perfectly for me as well. The problem is with Primary Ελληνικά (or Primary Slovenčina for your case).

**Comment by webmandesign** [comment]
Please provide admin access to your website so I can check personally. Use my contact page (see the link in previous reply) to send access details.

**Comment by webmandesign** [comment]
Oh, sorry, I can see you've already contacted me. I'm on it now.

**Comment by webmandesign** [comment]
When I check your website, everything seems to be working fine for me:

![polylang-issues](https://github.com/webmandesign/classic-menu-in-navigation-block/assets/2456735/90e57e88-b11e-443b-8d15-db0f0fd0919c)

Left is Greek homepage and English is on the right.

The only issue I can see is that the English menu is displaying "Languages" menu item. But this is not the issue with my plugin. Try to check your Polylang settings.
I can also see there are template parts for different languages in **Appearance → Editor → Patterns → Manage all template parts** so maybe that's what causing the issue? Please check your template parts and templates.

**Comment by Georgopoulos** [comment]
It was working fine because I had set a regular navigation block. Check what is happening when I choose the Primary English menu location from your plugin (I have just updated the website with this choice).

I have used 2 different templates for my homepage (and the rest of the pages as well). The problem lies in **Homepage EN**. Homepage EL works perfectly fine!

**Comment by webmandesign** [comment]
Can you let me know which template part should I edit?

**Comment by webmandesign** [comment]
I've just edited the "Header (Transparent)" template part and set main language menu location for the Navigation block and everything works perfectly fine now.

![123456](https://github.com/webmandesign/classic-menu-in-navigation-block/assets/2456735/a83cdde2-80e4-4955-b352-8075b23bbe4c)

I will see what I can do about making the plugin work with different, non-main menu locations for Polylang plugin. But if you use the main language one in every Navigation block, it will work. The main language for your website is set to Greek in Polylang settings.

**Comment by webmandesign** [comment]
Can you confirm it is working now?

**Comment by Georgopoulos** [comment]
It is almost working... If you see, it underlines the "Ελληνικά" menu option when the site is in English. I tried this yesterday but it looks a bit weird that you have to pick Primary Ελληνικά menu location - this one is for the Greek version of the site, not the English one, right?

<img width="1274" alt="image" src="https://github.com/webmandesign/classic-menu-in-navigation-block/assets/6174137/41b4a61c-4aaf-4a49-8e4e-e00cc933f7fc">

**Comment by Georgopoulos** [comment]
This problem (with the underlined language) happens only in the English homepage. For the rest of the pages it works correctly.

**Comment by Georgopoulos** [comment]
<img width="1277" alt="image" src="https://github.com/webmandesign/classic-menu-in-navigation-block/assets/6174137/b5c437e0-f664-4704-b08f-c1d3a8aa664b">

**Comment by webmandesign** [comment]
> If you see, it underlines the "Ελληνικά" menu option when the site is in English.

Underline is coming from your theme as a current menu item style. My plugin has no control over this, it is not an issue with my plugin. Contact your theme developer for help.

> I tried this yesterday but it looks a bit weird that you have to pick Primary Ελληνικά menu location - this one is for the Greek version of the site, not the English one, right?

I'm sorry, but this is more of a question for your multilingual plugin usage and setup. If you set Greek as default language and not English, it seems you need to use Greek for setting up classic menu fallback, you need to use main language. Like I've mentioned, I will see what I can do about this, but this behavior differs depending on what multilingual plugin you use.

> Screenshot

I'm sorry, I don't know what your you mean by the screenshot.

**Comment by Georgopoulos** [comment]
The screenshot was to show you that for the rest pages in English, it doesn't underline the language switcher option :)

So, to sum up: 

Regardless of how many languages you have, if you use Polylang, you always have to pick the Primary menu location of your default language for the Classic Menu, right?

Then I think you can close this issue, it seems that you've figured out the solution. 

Thank you again for the great support and your wonderful plugin! 🙏

**Comment by webmandesign** [comment]
> Regardless of how many languages you have, if you use Polylang, you always have to pick the Primary menu location of your default language for the Classic Menu, right?

Yes. This is also to assure your (any) multilingual plugin works as it should as it modifies the default menu location(s).
In classic themes you wouldn't even have an option to choose a different menu location and everything would be handled with multilingual plugin.

I've just updated the [plugin to version 1.0.1](https://github.com/webmandesign/classic-menu-in-navigation-block/releases) that is attempting to prevent the issue you described here.

Thanks for reporting the issue so I can make the plugin better.
